name: Build and SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run Unit Tests and SonarQube Scan
    runs-on: ubuntu-latest
    
    steps:
      # 1. Clonar el repositorio
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para un mejor análisis en SonarQube

      # 2. Instalar dependencias necesarias
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      # 3. Configurar y compilar el proyecto
      - name: Configure and Build
        run: |
          rm -rf build  # Eliminar build si ya existe para evitar errores
          mkdir build
          cd build
          cmake ..
          cmake --build .

      # 4. Ejecutar pruebas unitarias
      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure

      # 5. Escanear con SonarQube
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner

      # 6. (Opcional) Configurar Quality Gate para que falle si no cumple con los criterios de calidad
      # - name: SonarQube Quality Gate Check
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

